[package]
name = "fish-manpage-completions"
version = "0.1.0"
authors = ["Scott Steele <scottlsteele@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "*"
itertools = "*"
regex = "*"
lazy_static = "*"
bstr = "*"
libflate = "*"
bitflags = "1.2.1"

[dev-dependencies]
pretty_assertions = "*"
